### ISSUE TITLE
Studio App gets stuck at "Confirm New Site Configuration"

### ISSUE THREAD

**Issue by rodrigo-breia-lopes** [tirrel-corp/studio#9]
This the output at the dojo console:
```
>>  [%add-site name=%blog host='blog.rodrigo.systems' path=/ title='blog']
```

Clicking next won't do anything.

**Comment by rodrigo-breia-lopes** [comment]
F12 in browser, shows this in the browser console:
```
main.c6f28cae.js:2 Error: Ship unexpectedly closed the connection
    at onclose (main.c6f28cae.js:2:181608)
    at main.c6f28cae.js:2:177150
    at u (main.c6f28cae.js:2:147185)
    at Generator._invoke (main.c6f28cae.js:2:146938)
    at Generator.next (main.c6f28cae.js:2:147548)
    at pt (main.c6f28cae.js:2:171307)
    at o (main.c6f28cae.js:2:171511)
```
